name: CMake CI for Multi-Platform

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Build Directory
        id: vars
        shell: bash
        run: echo "build_dir=${{ github.workspace }}/build" >> $GITHUB_ENV

      - name: Configure CMake
        run: >
          cmake -B ${{ env.build_dir }} 
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} 
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} 
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} 
          -S ${{ github.workspace }}

      - name: Build Project
        run: cmake --build ${{ env.build_dir }} --config ${{ matrix.build_type }}

      - name: Run Tests
        working-directory: ${{ env.build_dir }}
        run: ctest --build-config ${{ matrix.build_type }}
